import { AppState, GovernmentVoucher, HouseholdMember, Transaction } from "./types";

export const TAN_FAMILY_MEMBERS: HouseholdMember[] = [
  {
    id: "mem-meiling",
    name: "Mei Ling",
    role: "manager",
    avatarBg: "bg-emerald-600",
    avatarText: "ML",
  },
  {
    id: "mem-weihan",
    name: "Wei Han",
    role: "co_manager",
    avatarBg: "bg-blue-600",
    avatarText: "WH",
  },
  {
    id: "mem-jiale",
    name: "Jia Le",
    role: "dependent",
    age: 11,
    avatarBg: "bg-amber-600",
    avatarText: "JL",
    personalBalance: 47.50,
    savingsGoal: {
      id: "goal-game",
      title: "New game",
      targetAmount: 60.00,
      currentAmount: 47.50,
      categoryIcon: "Gamepad2",
    },
  },
  {
    id: "mem-grandma",
    name: "Grandma Tan",
    role: "dependent",
    age: 72,
    avatarBg: "bg-purple-600",
    avatarText: "GT",
    personalBalance: 120.00,
  },
];

export const TAN_FAMILY_VOUCHERS: GovernmentVoucher[] = [
  {
    id: "vouch-cdc-supermarket",
    name: "CDC Supermarket Vouchers",
    category: "CDC_Supermarket",
    totalGranted: 150,
    balance: 85,
    expiryDate: "31 Dec 2026",
    daysRemaining: 12,
    description: "Jan 2026 Tranche for supermarket purchases (FairPrice, Sheng Siong, Prime, Giant).",
    acceptedMerchants: ["FairPrice", "Sheng Siong", "Giant", "Prime Supermarket"],
    isExpiringSoon: true,
  },
  {
    id: "vouch-climate",
    name: "Climate Vouchers",
    category: "Climate",
    totalGranted: 300,
    balance: 310, // including carryover/topup
    expiryDate: "31 Dec 2027",
    daysRemaining: 485,
    description: "Eligible for 5-tick energy-efficient refrigerators, washing machines, and LED lighting.",
    acceptedMerchants: ["Courts", "Best Denki", "Gain City", "Harvey Norman"],
    isExpiringSoon: false,
  },
  {
    id: "vouch-sg60",
    name: "SG60 Community Vouchers",
    category: "SG60",
    totalGranted: 300,
    balance: 217,
    expiryDate: "31 Dec 2026",
    daysRemaining: 120,
    description: "National Jubilee vouchers for heartland merchants and community services.",
    acceptedMerchants: ["Heartland Shops", "Community Clinics", "Neighborhood Grocers"],
    isExpiringSoon: false,
  },
];

export const TAN_FAMILY_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    date: "Today, 11:30 AM",
    description: "FairPrice Supermarket (Tampines)",
    amount: -24.50,
    category: "Groceries",
    source: "Cash Receipt",
    memberId: "mem-meiling",
    opportunityCostNote: "CDC Supermarket vouchers could have covered this $24.50 expense!",
  },
  {
    id: "tx-2",
    date: "Yesterday, 6:45 PM",
    description: "Pocket money to Jia Le (PayNow)",
    amount: -10.00,
    category: "Pocket Money",
    source: "PayNow",
    recipientId: "mem-jiale",
    memberId: "mem-meiling",
  },
  {
    id: "tx-3",
    date: "2 days ago",
    description: "SP Group Utilities Bill",
    amount: -138.20,
    category: "Utilities",
    source: "DBS",
    memberId: "mem-weihan",
  },
  {
    id: "tx-4",
    date: "3 days ago",
    description: "Bedok 85 Hawker Dinner",
    amount: -16.80,
    category: "Hawker & Dining",
    source: "PayNow",
    memberId: "mem-meiling",
  },
  {
    id: "tx-5",
    date: "4 days ago",
    description: "Salary Credit (Mei Ling)",
    amount: 2850.00,
    category: "Other",
    source: "DBS",
    memberId: "mem-meiling",
  },
];

export const INITIAL_APP_STATE: AppState = {
  currentPersonaId: "tan_family",
  householdName: "Tan Household",
  totalHouseholdBalance: 4285,
  thisMonthsSpend: 1940,
  members: TAN_FAMILY_MEMBERS,
  bankAccounts: [
    {
      id: "acc-dbs",
      bankName: "DBS Savings Plus",
      accountNumber: "•••-48291",
      accountType: "savings",
      balance: 3420,
      lastSynced: "Just now (Automated Sync)",
      icon: "Building2",
    },
    {
      id: "acc-ocbc",
      bankName: "OCBC 360 Account",
      accountNumber: "•••-91823",
      accountType: "current",
      balance: 865,
      lastSynced: "4 mins ago",
      icon: "Building2",
    },
    {
      id: "acc-paynow",
      bankName: "PayNow / PayLah! Linked Wallet",
      accountNumber: "+65 9123 4567",
      accountType: "wallet",
      balance: 240,
      lastSynced: "Real-time",
      icon: "Smartphone",
    },
  ],
  accounts: [
    {
      id: "acc-dbs",
      bankName: "DBS Savings Plus",
      accountNumber: "•••-48291",
      accountType: "savings",
      balance: 3420,
      lastSynced: "Just now (Automated Sync)",
      icon: "Building2",
    },
    {
      id: "acc-ocbc",
      bankName: "OCBC 360 Account",
      accountNumber: "•••-91823",
      accountType: "current",
      balance: 865,
      lastSynced: "4 mins ago",
      icon: "Building2",
    },
    {
      id: "acc-paynow",
      bankName: "PayNow / PayLah! Linked Wallet",
      accountNumber: "+65 9123 4567",
      accountType: "wallet",
      balance: 240,
      lastSynced: "Real-time",
      icon: "Smartphone",
    },
  ],
  transactions: TAN_FAMILY_TRANSACTIONS,
  vouchers: TAN_FAMILY_VOUCHERS,
  nudges: [
    {
      id: "nudge-init-1",
      type: "opportunity_cost",
      title: "Opportunity Cost Alert: Expiring CDC Vouchers",
      message: "You spent $24.50 in cash on groceries at FairPrice, but you have $85 in CDC Supermarket vouchers expiring in 12 days! Using your vouchers first protects your disposable cash.",
      severity: "alert",
      actionText: "View Expiring Vouchers",
      actionUrl: "#vouchers",
      timestamp: "Today",
    },
  ],
  currentSimulatedLocation: {
    id: "loc-fairprice",
    name: "NTUC FairPrice (Tampines Mall)",
    locationName: "Tampines Central",
    acceptedVouchers: ["CDC_Supermarket"],
    distanceMeters: 85,
    discountNote: "Accepts CDC Supermarket Vouchers (Balance: $85 left, Expires in 12 days)",
  },
};

/**
 * Persona 2: Marcus (24, Solo Gig Platform Worker - Lalamove)
 */
export const MARCUS_GIG_STATE: AppState = {
  currentPersonaId: "marcus_gig",
  householdName: "Marcus (Platform Worker)",
  totalHouseholdBalance: 2170,
  thisMonthsSpend: 1120,
  members: [
    {
      id: "mem-marcus",
      name: "Marcus",
      role: "manager",
      age: 24,
      avatarBg: "bg-indigo-600",
      avatarText: "M",
      workerType: "platform_worker",
      vehicleType: "motorcycle_pmd",
    },
  ],
  bankAccounts: [
    {
      id: "acc-posb",
      bankName: "POSB eMySavings",
      accountNumber: "•••-19283",
      accountType: "savings",
      balance: 1850,
      lastSynced: "10 mins ago",
      icon: "Building2",
    },
    {
      id: "acc-paynow-m",
      bankName: "PayNow / GrabPay Wallet",
      accountNumber: "+65 8234 5678",
      accountType: "wallet",
      balance: 320,
      lastSynced: "Real-time",
      icon: "Smartphone",
    },
  ],
  accounts: [
    {
      id: "acc-posb",
      bankName: "POSB eMySavings",
      accountNumber: "•••-19283",
      accountType: "savings",
      balance: 1850,
      lastSynced: "10 mins ago",
      icon: "Building2",
    },
    {
      id: "acc-paynow-m",
      bankName: "PayNow / GrabPay Wallet",
      accountNumber: "+65 8234 5678",
      accountType: "wallet",
      balance: 320,
      lastSynced: "Real-time",
      icon: "Smartphone",
    },
  ],
  gigProfile: {
    workerType: "platform_worker",
    platformName: "Lalamove & GrabFood",
    vehicleType: "motorcycle_pmd",
    fedaPercentage: 35, // 35% deduction for motorcycle
    grossWeeklyAverage: 820,
    safeWeeklySalary: 540,
    bufferSaved: 310,
    monthlyWisEligible: true,
    wisMonthlyAmount: 180,
    wisCashSplit: 18, // 10%
    wisMedisaveSplit: 162, // 90%
    wisPayoutStatus: [
      { month: "Jan 2026", status: "received", amount: 180 },
      { month: "Feb 2026", status: "received", amount: 180 },
      { month: "Mar 2026", status: "expected", amount: 180 },
      { month: "Apr 2026", status: "pending", amount: 180 },
    ],
  },
  transactions: [
    {
      id: "tx-m1",
      date: "Today, 2:00 PM",
      description: "Lalamove Weekly Payout (Gross: $890.00)",
      amount: 890.00,
      category: "Gig Payout",
      source: "PayNow",
      memberId: "mem-marcus",
      isGigIncome: true,
    },
    {
      id: "tx-m2",
      date: "Yesterday",
      description: "Esso Petrol Station (Motorcycle Refuel)",
      amount: -22.00,
      category: "Transport",
      source: "PayNow",
      memberId: "mem-marcus",
    },
    {
      id: "tx-m3",
      date: "3 days ago",
      description: "Kopitiam Chicken Rice & Kopi",
      amount: -6.50,
      category: "Hawker & Dining",
      source: "Cash Receipt",
      memberId: "mem-marcus",
    },
  ],
  vouchers: [
    {
      id: "vouch-wis-monthly",
      name: "Workfare Income Supplement (WIS / PCTS)",
      category: "Workfare_WIS",
      totalGranted: 2160,
      balance: 180,
      expiryDate: "Monthly Payout (Mar 2026)",
      daysRemaining: 18,
      description: "Platform Workers CPF Transition Support. $18.00 Cash + $162.00 MediSave split.",
      acceptedMerchants: ["Direct Bank Deposit / CPF Board"],
      isExpiringSoon: false,
    },
    {
      id: "vouch-marcus-cdc",
      name: "CDC Vouchers (Solo Citizen)",
      category: "CDC_Supermarket",
      totalGranted: 300,
      balance: 120,
      expiryDate: "31 Dec 2026",
      daysRemaining: 120,
      description: "CDC Supermarket vouchers for solo household.",
      acceptedMerchants: ["FairPrice", "Sheng Siong"],
      isExpiringSoon: false,
    },
  ],
  nudges: [
    {
      id: "nudge-m-1",
      type: "gig_buffer",
      title: "Weekly Income Smoothed ($540 Safe Salary)",
      message: "This week's gross payout was $890. After 35% FEDA and CPF, your $350 surplus was deposited into your Lean-Week Buffer (Total buffer: $310).",
      severity: "info",
      timestamp: "Today",
    },
    {
      id: "nudge-m-2",
      type: "opportunity_cost",
      title: "WIS March Payout Confirmed",
      message: "Your March Workfare ($180: $18 Cash + $162 MediSave) is on track to deposit on the 28th.",
      severity: "info",
      timestamp: "Yesterday",
    },
  ],
  currentSimulatedLocation: null,
};

/**
 * Persona 3: Jia Le (Age 11, Child Dependent)
 */
export const JIA_LE_STATE: AppState = {
  currentPersonaId: "jia_le",
  householdName: "Jia Le's Pocket Ledger",
  totalHouseholdBalance: 47.50,
  thisMonthsSpend: 15.50,
  members: [
    {
      id: "mem-jiale",
      name: "Jia Le",
      role: "dependent",
      age: 11,
      avatarBg: "bg-amber-600",
      avatarText: "JL",
      personalBalance: 47.50,
      savingsGoal: {
        id: "goal-game",
        title: "Wilson NCAA Basketball",
        targetAmount: 60.00,
        currentAmount: 47.50,
        categoryIcon: "🏀",
      },
    },
  ],
  bankAccounts: [
    {
      id: "acc-smart-buddy",
      bankName: "My Pocket Money (Smart Buddy Card)",
      accountNumber: "JL-8291",
      accountType: "wallet",
      balance: 47.50,
      lastSynced: "Real-time",
      icon: "CreditCard",
    },
  ],
  accounts: [
    {
      id: "acc-smart-buddy",
      bankName: "My Pocket Money (Smart Buddy Card)",
      accountNumber: "JL-8291",
      accountType: "wallet",
      balance: 47.50,
      lastSynced: "Real-time",
      icon: "CreditCard",
    },
  ],
  transactions: [
    {
      id: "tx-jl-1",
      date: "Yesterday",
      description: "Pocket money from Mum",
      amount: 10.00,
      category: "Pocket Money",
      source: "PayNow",
      memberId: "mem-jiale",
    },
    {
      id: "tx-jl-2",
      date: "3 days ago",
      description: "Canteen snack (Waffle & Milo)",
      amount: -2.50,
      category: "Hawker & Dining",
      source: "Cash Receipt",
      memberId: "mem-jiale",
    },
    {
      id: "tx-jl-3",
      date: "1 week ago",
      description: "Birthday money from Grandma",
      amount: 20.00,
      category: "Other",
      source: "Cash Receipt",
      memberId: "mem-jiale",
    },
    {
      id: "tx-jl-4",
      date: "2 weeks ago",
      description: "School bookstore eraser & notebook",
      amount: -3.00,
      category: "Other",
      source: "Cash Receipt",
      memberId: "mem-jiale",
    },
  ],
  vouchers: [],
  nudges: [
    {
      id: "nudge-jl-1",
      type: "opportunity_cost",
      title: "Great job saving! 🏀",
      message: "You have saved $47.50! Only $12.50 more to reach your 'Wilson NCAA Basketball' goal!",
      severity: "info",
      timestamp: "Today",
    },
  ],
  currentSimulatedLocation: null,
};

/**
 * Persona 4: Alex (Solo Young Adult)
 */
export const ALEX_STATE: AppState = {
  currentPersonaId: "alex_young_adult",
  householdName: "Alex (Young Adult)",
  totalHouseholdBalance: 5200,
  thisMonthsSpend: 1450,
  members: [
    {
      id: "mem-alex",
      name: "Alex",
      role: "manager",
      age: 26,
      avatarBg: "bg-teal-600",
      avatarText: "A",
      workerType: "regular_income",
    },
  ],
  bankAccounts: [
    {
      id: "acc-posb-alex",
      bankName: "POSB Savings Account",
      accountNumber: "•••-55412",
      accountType: "savings",
      balance: 5200,
      lastSynced: "Automated Sync",
      icon: "Building2",
    },
  ],
  accounts: [
    {
      id: "acc-posb-alex",
      bankName: "POSB Savings Account",
      accountNumber: "•••-55412",
      accountType: "savings",
      balance: 5200,
      lastSynced: "Automated Sync",
      icon: "Building2",
    },
  ],
  transactions: [
    {
      id: "tx-a1",
      date: "Today, 1:15 PM",
      description: "Cold Storage Groceries",
      amount: -34.80,
      category: "Groceries",
      source: "DBS",
      memberId: "mem-alex",
    },
    {
      id: "tx-a2",
      date: "2 days ago",
      description: "MRT & Bus Fare (SimplyGo)",
      amount: -18.20,
      category: "Transport",
      source: "DBS",
      memberId: "mem-alex",
    },
    {
      id: "tx-a3",
      date: "5 days ago",
      description: "Monthly Salary Credit",
      amount: 3800.00,
      category: "Other",
      source: "DBS",
      memberId: "mem-alex",
    },
  ],
  vouchers: [
    {
      id: "vouch-alex-cdc",
      name: "CDC Vouchers 2026",
      category: "CDC_Supermarket",
      totalGranted: 300,
      balance: 150,
      expiryDate: "31 Dec 2026",
      daysRemaining: 120,
      description: "CDC Supermarket and Hawker voucher tranche.",
      acceptedMerchants: ["FairPrice", "Sheng Siong", "Hawkers"],
      isExpiringSoon: false,
    },
  ],
  nudges: [],
  currentSimulatedLocation: null,
};
